// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​e​s​t​ ​1
	 */
	test1: string
	/**
	 * T​e​s​t​ ​2
	 */
	test2: string
	/**
	 * T​e​s​t​ ​3
	 */
	test3: string
}

export type TranslationFunctions = {
	/**
	 * Test 1
	 */
	test1: () => LocalizedString
	/**
	 * Test 2
	 */
	test2: () => LocalizedString
	/**
	 * Test 3
	 */
	test3: () => LocalizedString
}

export type Formatters = {}
